version: '3.8'
services:
  nginx-server:
    image: nginx:1.22.1-alpine
    container_name: nginx-web1
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    networks: #网络2，使用自定义的网络，如果网络不存在则会自动创建该网络并分配子网,并且容器会有两块网卡
      - front
      - backend
    links:
      - tomcat-server

  tomcat-server:
    image: tomcat:8.5.41-alpine
    container_name: tomcat-app1
    volumes: # 挂载本地项目目录到tomcat中
      - /data/tomcat/webapps:/usr/local/tomcat/webapps/myweb
    networks: #网络2，使用自定义的网络，如果网络不存在则会自动创建该网络并分配子网,并且容器会有一块网卡
      - backend

networks:
  front: #自定义前端服务网络,需要docker-compose创建
    driver: bridge
  backend:  #自定义后端服务的网络,要docker-compose创建
    driver: bridge